name: Portfolio Unit Tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependancies
      - run: npm ci

      - name: Run Tests
      - run: npm run test-ci
